on: workflow_dispatch

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: RTF_DEV_RASD
          password: letmein
          url: jdbc:oracle:thin:@exacc14db04vm01-vip.au.cbainet.com:1521/GTRS_DEV2.cba.com.au
