on: workflow_dispatch

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
      - uses: liquibase-github-actions/update-sql@v4.27.0
        with:         
          classpath: 'example/changelogs'
          changeLogFile: 'samplechangelog.h2.sql'
          username: liquibase
          password: password
          url: jdbc:h2:file:./h2tutorial
